name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - bokeh
  - cudnn=7.6.5__cuda-10.1
  - cudatoolkit=10.1
  - cupy
  - dask
  - dask-ml
  - dask-labextension
  - datashader
  - featuretools
  - gh
  - git
  - h5py
  - holoviews
  - hvplot
  - imbalanced-learn
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-lsp
  - jupyterlab-nvdashboard
  - lightgbm
  - matplotlib
  - nccl
  - numba
  - numpy
  - optuna
  - pandas
  - panel
  - python=3.7
  - pip
  - pip:
    - -r requirements.txt
  - pyarrow
  - python-language-server
  - pyviz_comms
  - scikit-learn
  - scipy
  - shap
  - tensorboard
  - tensorflow=2.3.0
  - tensorflow--addons=0.11.2
  - umap-learn
  - wandb
  - xarray
  - xeus-python
  - xgboost
